### ISSUE TITLE
feat: local-environment

### ISSUE THREAD

**Issue by ahmedrowaihi** [badass-courses/course-builder#198]
### Describe the feature you'd like to request

in my opinion, this setup makes it crazy hard to convince someone to go and provision all these services just to start exploring this project in local development 
```
[next] ❌ Invalid environment variables: {
[next]   STRIPE_SECRET_TOKEN: [ 'Required' ],
[next]   STRIPE_WEBHOOK_SECRET: [ 'Required' ],
[next]   DATABASE_URL: [ 'Required' ],
[next]   OPENAI_API_KEY: [ 'Required' ],
[next]   INNGEST_EVENT_KEY: [ 'Required' ],
[next]   INNGEST_SIGNING_KEY: [ 'Required' ],
[next]   MUX_SECRET_KEY: [ 'Required' ],
[next]   MUX_ACCESS_TOKEN_ID: [ 'Required' ],
[next]   OPENAI_MODEL_ID: [ 'Required' ],
[next]   UPSTASH_REDIS_REST_URL: [ 'Required' ],
[next]   UPSTASH_REDIS_REST_TOKEN: [ 'Required' ],
[next]   DEEPGRAM_API_KEY: [ 'Required' ],
[next]   UPLOADTHING_URL: [ 'Required' ],
[next]   POSTMARK_API_KEY: [ 'Required' ],
[next]   POSTMARK_WEBHOOK_SECRET: [ 'Required' ],
[next]   NEXT_PUBLIC_APP_NAME: [ 'Required' ],
[next]   NEXT_PUBLIC_PARTYKIT_ROOM_NAME: [ 'Required' ],
[next]   NEXT_PUBLIC_PARTY_KIT_URL: [ 'Required' ],
[next]   NEXT_PUBLIC_URL: [ 'Required' ],
[next]   NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: [ 'Required' ],
[next]   NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: [ 'Required' ],
[next]   NEXT_PUBLIC_SUPPORT_EMAIL: [ 'Required' ],
[next]   NEXT_PUBLIC_SITE_TITLE: [ 'Required' ]
[next] }
```

### Describe the solution you'd like to see

setting up mocks/container replacments for services in dev mode 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by joelhooks** [comment]
ya, it's wild lol

this project is what we use internally for the business so it's not really intended for "messing around"

**Comment by joelhooks** [comment]
i'd say there is a development environment is present, just not available to you

--- original message ---
On August 1, 2024 at 5:11 PM PDT ***@***.*** wrote:



> this project is what we use internally for the business so it's not really intended for "messing around"


interesting stuff, a business that develops in production.

No mocks, No dev env, all stuff depends on vendors.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you modified the open/close state.Message ID: ***@***.***>
--- end of original message ---
