### ISSUE TITLE
AutoComplete video lessons when the video is done

### ISSUE THREAD

**Issue by joelhooks** [badass-courses/course-builder#251]
a configurable option that would automatically mark an individual lesson complete when a video finishes playing.

**Comment by vojtaholik** [comment]
I made it tied to binge mode in this pnjs implementation: https://github.com/badass-courses/course-builder/pull/259

I think it'd be interesting to make it configurable on module (or resource type) level. and perhaps overwrite it from product level with an env flag or something.

**Comment by joelhooks** [comment]
i think pnjs should autocomplete on video end in general and not just with autoplay turned on
